;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-char
	evil-exit-visual-state
	evil-force-normal-state
	evil-forward-char
	evil-goto-first-line
	evil-mouse-drag-region
	evil-next-line
	evil-normal-state
	evil-previous-line
	))

(setq mc/cmds-to-run-once
      '(
	evil-insert
	))
