;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-buffer
	c-electric-slash
	comment-line
	evil-backward-char
	evil-exit-visual-state
	evil-force-normal-state
	evil-forward-char
	evil-goto-first-line
	evil-mouse-drag-region
	evil-next-line
	evil-normal-state
	evil-previous-line
	evil-search-forward
	ignore
	indent-for-tab-command
	indent-rigidly
	indent-rigidly-right
	jedi:goto-definition
	kill-region
	mouse-select-window
	mouse-set-region
	overwrite-mode
	python-indent-dedent-line
	suspend-frame
	tabbar-select-tab-callback
	))

(setq mc/cmds-to-run-once
      '(
	evil-insert
	mouse-drag-header-line
	))
